Repository uprm-inso4117-2023-2024-s2/semester-project-study-pet, pull requests merged in 2024-04, with the labels that each got.

#301 Eat minigame availability
  components/Pet.jsx
  components/eatingMinigame.jsx
  pages/Eat.js
  pages/HomePage.js
  pages/Stats.js
  pages/notifications.js
Labels: FLASHCARD Team

#331 Sleep restrictions and additional Fuzzy testing
  __tests__/petShopFuzzy.test.js
  __tests__/sleepScheduleFuzzy.test.js
  __tests__/utils/seleniumTestUtils.js
  components/Pet.jsx
  components/bathing.jsx
  components/eatingMinigame.jsx
  components/minigame.jsx
  components/sleepScheduleStorage.js
  pages/Bath.js
  pages/Eat.js
  pages/Game.js
  pages/HomePage.js
  pages/PlayerStats.js
  pages/Shop.js
  utils/shopAssets.js
  utils/sleepSchedule.js
Labels: bug, enhancement, PET Team

#336 Fix broken bath tests
  __tests__/FuzzyTesting/eat.test.js
  __tests__/bath.test.js
  package-lock.json
Labels: bug

#338 Fix BDD tests
  features/step_definitions/stepdefs.js
  package-lock.json
Labels: bug

#332 updates hoare logic to use assertion as a approximation of events
  components/Pet.jsx
Labels: enhancement

#329 Health hunger balance
  components/Pet.jsx
  components/bathing.jsx
  components/eatingMinigame.jsx
  components/happinessStorage.jsx
  components/hungerStorage.jsx
  components/minigame.jsx
  pages/Stats.js
Labels: FLASHCARD Team
