Repository uprm-inso4117-2023-2024-s2/semester-project-study-pet, pull requests merged in 2024-03, with the labels that each got.

#202 Care mistakes added
  components/Pet.jsx
  pages/Stats.js
Labels: USER Team

#208 `happiness` aspect
  components/Pet.jsx
  components/eatingMinigame.jsx
  components/happinessStorage.jsx
  components/hungerStorage.jsx
  package.json
  pages/Eat.js
  pages/Stats.js
Labels: enhancement, FLASHCARD Team

#227 After pet creation study set creation
  App.js
  package-lock.json
  package.json
  pages/CreatePetScreen.js
  pages/Flashcards.js
  pages/PetToStudySetCreation.js
Labels: enhancement

#288 Fixed notifications, work on android and web version
  pages/notifications.js
Labels: bug
